#!/bin/bash

SOURCE="$1"
TARGET="$2"

IGNOREGIT=true
FILTER=false

mkdir -p "$TARGET"

function ignoregit {
	if $IGNOREGIT; then
		grep -Ev '\.git(/|$)'
	else
		cat
	fi
}

if ls "$SOURCE/.stow-local-ignore" &> /dev/null; then
	FILTER=true
fi


find -L "$SOURCE" | ignoregit | 
    while read -r f; do 
		NAME=${f/$SOURCE//}

		if [[ $FILTER == true ]]; then
			if [[ $f == "$SOURCE/.stow-local-ignore" ]]; then
				continue
			fi

			NAME="$(sed -e 's/^\/.//' <<< $NAME)"
			if [[ -n $(awk -v input="$NAME" 'index(input, $0) == 1' "$SOURCE/.stow-local-ignore") ]] ; then
				echo "ignoring $f"
				continue
			fi
		fi

		if [ -d "$f" ]; then
			mkdir -p "$TARGET/$NAME"
		fi


		if [ -f "$f" ]; then
			ln -snf "$(realpath "$f")" "$TARGET/$NAME"
		fi
	done
